### ISSUE TITLE
RocksDB 版本更新？

### ISSUE THREAD

**Issue by jojo59516** [Qihoo360/nemo-rocksdb#1]
我们目前需要使用最新版的 rocksdb，而 rocksdb 的最新版本某些函数有改动，与 nemo-rocksdb 当前函数接口不兼容：
**file_util.h:** 
Status CopyFile(Env* env, const std::string& source, const std::string& destination, uint64_t size);
最新版 rocksdb 中变为：
Status CopyFile(Env* env, const std::string& source, const std::string& destination, uint64_t size**, bool use_fsync**);

**db_nemo_impl.h:**
virtual Status Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, std::string* value) override;
最新版 rocksdb 中祖父类 StackableDB 中的声明是：
virtual Status Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, **PinnableSlice* value**) override;

不知可否支持一下最新版本？

**Comment by KernelMaker** [comment]
1. 你们用的是nemo-rocksdb的哪个分支？推荐使用public-release分支
2. nemo-rocksdb与最新版rocksdb的兼容性应该不存在问题，DBNemo的Get是继承自rocksdb的DB，它里面是包含(string* value)定义的Get接口，我们测试使用最新rocksdb(9f2cc5)来编译，不存在不兼容的问题
3. 新Get接口我们也会尽快支持

谢谢关注

**Comment by KernelMaker** [comment]
nemo-rocksdb的master分支的确存在CopyFile不兼容的问题，我已经在代码中加了宏去区分，目前已经支持rocksdb的最新提交，你试试。

PS: nemo-rocksdb的master分支是给我们内部nemo使用的

**Comment by jojo59516** [comment]
1. 我们 fork 了你们的 pika，更新了 rocksdb 至最新版本出现的问题，所以 nemo-rocksdb 默认是 master 分支
2. rockdb v5.0.1（nemo-rocksdb 中使用的版本）中的声明是
`virtual Status StackableDB::Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, std::string* value) override;`
所以
`virtual Status DBNemoImpl::Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, std::string* value) override;`
重写了 StackableDB::Get()，而 rocksdb 更新至最新版之后 StackableDB 类中的声明变成了
`virtual Status StackableDB::Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, PinnableSlice value*) override;`
导致现在 DBNemoImpl::Get() 重写了 DB::Get()：
`virtual Status DB::Get(const ReadOptions& options, ColumnFamilyHandle* column_family, const Slice& key, std::string* value) = 0;`
所以我担心的是这样不会有问题么？

**Comment by KernelMaker** [comment]
已经搞定了，你试试吧
